/**
 * SongBookService.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StructuredPartDTO } from './structuredPartDTO';
import { StructuredSlideDTO } from './structuredSlideDTO';

export interface StructuredSongDTO { 
    id?: string;
    number?: string;
    title?: string;
    originalTitle?: string;
    author?: string;
    parts?: Array<StructuredPartDTO>;
    partOrder?: Array<string>;
    slides?: Array<StructuredSlideDTO>;
}